schema_version = "1.0.0"
id = "Single-Point-Curve"
type = "add-on"

[blender]
name = "Single Point Curve"
version = "1.0.0"
blender_version_min = "4.4.0"
tagline = "Adds a single control point with collapsed handles"
description = "Creates a minimal curve object with a single control point and collapsed handles, perfect as a starting point for building custom curves."
author = "Amir Diab"
maintainer = "Amir Diab <mct77077787@gmail.com>"
license = ["SPDX:GPL-3.0-or-later"]
category = "Add Curve"

doc_url = "https://github.com/Ashtzaph/Single-Point-Curve"
tracker_url = "https://github.com/Ashtzaph/Single-Point-Curve/issues"
support_url = "https://github.com/Ashtzaph/Single-Point-Curve/discussions"

[platform]
python = ">=3.10"

[files]
include = [
    "*.py",
    "README.md",
    "LICENSE"
]

exclude = [
    "__pycache__/*",
    "*.blend*"
]
